const getRandomId = () => {
    return Math.random()*10000000
}

export const eventsPlaceholder = [
    {
        "id": 1,
        "name": "Unexpected Party at Bag End",
        "starts": "2024-11-21T12:30:00",
        "createdBy": "u1t3eZPwcFZiyxJqRzIwcrxmmwX2",
        "favorites": ["u1t3eZPwcFZiyxJqRzIwcrxmmwX2"],
        "location": "Bag End, Hobbiton, The Shire",
    },
    {
        "id": 2,
        "name": "Trolls Encounter",
        "starts": "2024-11-22T09:15:00", 
        "createdBy": "O5aAoLGOhqbaRT4twdpV22YWiM13",
        "favorites": [],
        "location": "East of Rivendell, Misty Mountains",
    },
    {
        "id": 3,
        "name": "Battle of Moria",
        "starts": "2024-11-23T14:45:00",
        "createdBy": "u1t3eZPwcFZiyxJqRzIwcrxmmwX2",
        "favorites": ["O5aAoLGOhqbaRT4twdpV22YWiM13","u1t3eZPwcFZiyxJqRzIwcrxmmwX2"],
        "location": "Mines of Moria, Misty Mountains",
    },
    {
        "id": 4,
        "name": "Council of Elrond",
        "starts": "2024-11-24T11:00:00",
        "createdBy": "O5aAoLGOhqbaRT4twdpV22YWiM13",
        "favorites": [],
        "location": "Rivendell, House of Elrond",
    },
    {
        "id": 5,
        "name": "Breaking of the Fellowship",
        "starts": "2024-11-25T16:30:00",
        "createdBy": "u1t3eZPwcFZiyxJqRzIwcrxmmwX2",
        "favorites": [],
        "location": "Amon Hen, Gondor",
    },
    {
        "id": 6,
        "name": "Helm's Deep Battle",
        "starts": "2024-11-26T10:00:00",
        "createdBy": "O5aAoLGOhqbaRT4twdpV22YWiM13",
        "favorites": [],
        "location": "Helm's Deep, Rohan",
    },
    {
        "id": 7,
        "name": "Battle of Pelennor Fields",
        "starts": "2024-11-27T08:45:00",
        "createdBy": "u1t3eZPwcFZiyxJqRzIwcrxmmwX2",
        "favorites": ["O5aAoLGOhqbaRT4twdpV22YWiM13"],
        "location": "Pelennor Fields, Gondor",
    },
    {
        "id": 8,
        "name": "Riddles in the Dark",
        "starts": "2024-11-28T13:20:00",
        "createdBy": "O5aAoLGOhqbaRT4twdpV22YWiM13",
        "favorites": ["u1t3eZPwcFZiyxJqRzIwcrxmmwX2"],
        "location": "Goblin Caves, Misty Mountains",
    },
    {
        "id": 9,
        "name": "Escape from Goblin Town",
        "starts": "2024-11-29T15:55:00",
        "createdBy": "u1t3eZPwcFZiyxJqRzIwcrxmmwX2",
        "favorites": ["u1t3eZPwcFZiyxJqRzIwcrxmmwX2"],
        "location": "Goblin Town, Underground Misty Mountains",
    },
    {
        "id": 10,
        "name": "Battle of the Five Armies",
        "starts": "2024-11-30T07:30:00",
        "createdBy": "O5aAoLGOhqbaRT4twdpV22YWiM13",
        "favorites": [],
        "location": "Lonely Mountain, Dale",
    },
    {
        "id": 11,
        "name": "Siege of Gondor",
        "starts": "2024-12-01T12:15:00",
        "createdBy": "u1t3eZPwcFZiyxJqRzIwcrxmmwX2",
        "favorites": ["O5aAoLGOhqbaRT4twdpV22YWiM13","u1t3eZPwcFZiyxJqRzIwcrxmmwX2"],
        "location": "Minas Tirith, Gondor",
    },
    {
        "id": 12,
        "name": "Flight to the Ford",
        "starts": "2024-12-02T16:00:00",
        "createdBy": "O5aAoLGOhqbaRT4twdpV22YWiM13",
        "favorites": ["O5aAoLGOhqbaRT4twdpV22YWiM13"],
        "location": "Road to Rivendell, near Bruinen River",
    },
    {
        "id": 13,
        "name": "Battle of the Pelennor Fields",
        "starts": "2024-12-03T09:45:00",
        "createdBy": "u1t3eZPwcFZiyxJqRzIwcrxmmwX2",
        "favorites": [],
        "location": "Pelennor Fields, Outside Minas Tirith",
    },
    {
        "id":14,
        "name": "Destruction of the One Ring",
        "starts": "2024-12-04T11:30:00",
        "createdBy": "O5aAoLGOhqbaRT4twdpV22YWiM13",
        "favorites": ["O5aAoLGOhqbaRT4twdpV22YWiM13","u1t3eZPwcFZiyxJqRzIwcrxmmwX2"],
        "location": "Mount Doom, Mordor",
    }
]